---
title: "generate_ancestral_states"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr) 
opts_knit$set(echo = FALSE,warning = FALSE, message = FALSE,error=FALSE,comment=NA) 
opts_chunk$set(echo = FALSE,warning = FALSE, message = FALSE,error=FALSE,comment=NA) 
knitr::opts_knit$set(root.dir = '~/Desktop/gl_mount/Analysis/Phyloaware/joint-uncertainty-ms/') 
```

```{r environment, echo=T, message=FALSE, include=T, results=T}
#Packages
packages <- c("tidyverse",'corHMM','proxy','dbscan','Rtsne','phyloAMR') 

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Print environment
set.seed(0104) 
Sys.info()
sessionInfo()
```

# Load data
```{r}  
phy <- ape::read.tree("./data/empirical/tree/tree.treefile")
dat <- readRDS("./data/empirical/dataset/df.RDS")
dat <- dat[match(phy$tip.label, dat[['isolate_no']]), ]
```

# Generate ASR model
```{r}
# Data curation
cor_dat <- data.frame(sp = dat$isolate_no, d = dat$blbli_dich_num, row.names = dat$isolate_no) 
cor_dat <- cor_dat[match(phy$tip.label, cor_dat[['sp']]), ]

# Running to identify best ARD model
focal <- corHMM(phy = phy,data =  cor_dat, rate.cat = 1, model = "ER", node.states = "joint", upper.bound = 1e100, lower.bound = 1e-9, root.p = "maddfitz")

saveRDS(object = focal, file = "./data/empirical/joint_reconstruction/focal_asr.RDS")
```

# Visualize ASR model
```{r}
state_cols <- RColorBrewer::brewer.pal(2, "Set1")
plot(phy, no.margin = TRUE,show.tip.label = F)
tiplabels(pch = 21, bg = state_cols[as.numeric(focal$data.legend[,2])], cex = 0.75)
nodelabels(pch = 21, bg = state_cols[focal$states], cex = 0.75)
```

# Joint uncertainty calculations
## To generate more ancestral state reconstructins, I increased batch size to 250 and max samples to 10k, giving roughly 500 reconstructions
```{r} 
joint_ci <- corHMM:::compute_joint_ci(
  focal, 
  batch_size = 100,  
  break_threshold = 0,
  max_samples = 1000,
  ncores = 7)

saveRDS(joint_ci,"./data/empirical/joint_reconstruction/joint_uncertainty_asr.RDS")
```

# Identify best joint call, state dataframe, and phylogenetic distance matrix using node distance
```{r} 
state_df <- joint_ci$state_df
state_df_matrix <- as.matrix(state_df)

saveRDS(state_df_matrix,"./data/empirical/joint_reconstruction/joint_uncertainty_asr_state_matrix.RDS")
```