---
title: "Reconstruction stats across genotype and phenotype"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr) 
opts_knit$set(echo = FALSE,warning = FALSE, message = FALSE,error=FALSE,comment=NA) 
opts_chunk$set(echo = FALSE,warning = FALSE, message = FALSE,error=FALSE,comment=NA) 
knitr::opts_knit$set(root.dir = '~/Desktop/gl_mount/Analysis/Phyloaware/joint-uncertainty-ms/') 
```

```{r environment, echo=T, message=FALSE, include=T, results=T}
#Packages
packages <- c("tidyverse",'corHMM','proxy','dbscan','Rtsne','phyloAMR','kableExtra','gontjesr') 

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Print environment
set.seed(0104) 
Sys.info()
sessionInfo()
```

# Load data
```{r}  
phy <- ape::read.tree("./data/empirical/tree/tree.treefile")
dat <- readRDS("./data/empirical/dataset/df.RDS")
dat <- dat[match(phy$tip.label, dat[['isolate_no']]), ]
```


# Load data
```{r}  
phy <- ape::read.tree("./data/empirical/tree/tree.treefile")
dat <- readRDS("./data/empirical/dataset/df.RDS")
dat <- dat[match(phy$tip.label, dat[['isolate_no']]), ]
```

```{r}
genotypes <- readRDS("./data/empirical/resistance_genotypes/resistance_genotypes.RDS") 
genotypes <-  genotypes %>% .[match(phy$tip.label,.[['isolate_no']]),]

df <- left_join(dat,genotypes)
```

# Reconsctructions
```{r}
focals <- readRDS("~/Desktop/gl_mount/Analysis/Phyloaware/joint-uncertainty-ms/data/empirical/joint_reconstruction/phenotype_genotype_focal_asrs.RDS")
joint_uncs <- readRDS("~/Desktop/gl_mount/Analysis/Phyloaware/joint-uncertainty-ms/data/empirical/joint_reconstruction/phenotype_genotype_joint_uncertainty_asrs.RDS")
```

# Extract stats
```{r}
joint_unc_stats <- function(name,joint_uncs){
  trait = name
  n_reconstructions = length(joint_uncs[[name]]$lnliks)
  return(  data.frame(trait = name, n_reconstructions = n_reconstructions))
}

frequency <- lapply(names(joint_uncs),joint_unc_stats,joint_uncs) %>% do.call(rbind,.) 

frequency %>% favorite_kable() 
```

