---
title: "table_resistance_alternative_recon_statistics"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---
```{r setup, include=FALSE}
require(knitr) 
opts_knit$set(echo = FALSE,warning = FALSE, message = FALSE,error=FALSE,comment=NA) 
opts_chunk$set(echo = FALSE,warning = FALSE, message = FALSE,error=FALSE,comment=NA) 
knitr::opts_knit$set(root.dir = '~/Desktop/gl_mount/Analysis/Phyloaware/joint-uncertainty-ms/') 
```


```{r environment, echo=T, message=FALSE, include=T, results=T}
#Packages
packages <- c("tidyverse",'corHMM','phyloAMR','gontjesr','kableExtra') 

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Source functions
source("./lib/consistent_themes.R")

# Print environment
set.seed(0104) 
Sys.info()
sessionInfo()
```

# Load data
## Dataset
```{r} 
dat <- readRDS("./data/empirical/dataset/df.RDS")
phy <- read.tree("./data/empirical/tree/tree.treefile") 
dbres <- readRDS("./data/empirical/joint_reconstruction/joint_uncertainty_asr_clustering_optimal.RDS")
```

## Clustering stats
```{r}
cluster_analysis_df <- readRDS("./data/empirical/phyloAMR/phenotype_genotype_joint_uncertainty_asr_clustering_statistics.RDS")
blbli_cluster_analysis_df <- cluster_analysis_df %>% subset(trait == 'blbli_dich_num')
 
dbcluster_names <- dbres$cluster %>% `names<-`(seq_len(length(.)))
blbli_cluster_analysis_df$pheno_number <- sapply(blbli_cluster_analysis_df$reconstruction_axis,FUN=function(x){
  if(grepl("alt_recon",x)){
    
  gsub("alt_recon_","",x)
  } else {
    x
  } 
})  

blbli_cluster_analysis_df$pheno_cluster <- sapply(blbli_cluster_analysis_df$pheno_number,FUN=function(x){
  if(!grepl("focal",x)){
    dbcluster_names[names(dbcluster_names) == x]
  } else {
    x
  }
})
 

get_median_min_max_values <- function(variable,dataset){
 variable_summary <- dataset %>%
  group_by(pheno_cluster) %>% select(variable,pheno_cluster) %>% 
  summarise(
    median_value = median(get(variable), na.rm = TRUE),
    min_value = min(get(variable), na.rm = TRUE),
    max_value = max(get(variable), na.rm = TRUE)
  ) %>%
  mutate(
    summary_string = sprintf("%.1f (%.1f - %.1f)", median_value, min_value, max_value)
  ) %>% ungroup %>% select(pheno_cluster,summary_string) %>% `colnames<-`(c("pheno_cluster",paste0(variable))) 
}

variable_cluster_stats  <- c("phylogenetic_events","singletons","singleton_isolates","clusters","cluster_isolates","cluster_size_median")

cluster_stats <- lapply(variable_cluster_stats,get_median_min_max_values,dataset=blbli_cluster_analysis_df) %>% reduce(
  .,
  ~ left_join(.x, .y, by = "pheno_cluster")
)
```

## Transition stats
```{r}
transition_df <- readRDS("./data/empirical/phyloAMR/joint_states_reconstruction_transition_statistics.RDS") 
blbli_transition_analysis_df <- transition_df %>% .[["blbli_dich_num"]] 
 
blbli_transition_analysis_df$pheno_number <- sapply(blbli_transition_analysis_df$reconstruction,FUN=function(x){
  if(grepl("alt_recon",x)){
    
  gsub("alt_recon_","",x)
  } else {
    x
  } 
})  

blbli_transition_analysis_df$pheno_cluster <- sapply(blbli_transition_analysis_df$pheno_number,FUN=function(x){
  if(!grepl("focal",x)){
    dbcluster_names[names(dbcluster_names) == x]
  } else {
    x
  }
})

variable_transition_stats  <- c("transitions","gains","gains_tip","losses","losses_tip","continuations_present")

transition_stats <- lapply(variable_transition_stats,get_median_min_max_values,dataset=blbli_transition_analysis_df) %>% reduce(
  .,
  ~ left_join(.x, .y, by = "pheno_cluster")
)
```
## Number reconstructions
```{r}
num_recons <- blbli_transition_analysis_df %>% group_by(pheno_cluster) %>% summarise (`Reconstructions` = n())
```



# Merged table
```{r}
table <- left_join(num_recons,cluster_stats) %>% left_join(.,transition_stats) 
table$pheno_cluster <- recode(table$pheno_cluster,"focal_states" ="Best joint model",
                                             "1" ="Alternative axis 1",
                                             "2" ="Alternative axis 2",
                                             "3" ="Alternative axis 3",
                                             "4" ="Alternative axis 4",
                                             "5" ="Alternative axis 5") 

colnames(table) <- c("Phenotype axis","Reconstructions","Phylogentic events","Singletons","Singleton isolates","Clusters","Cluster isolates","Cluster size (median)","Transitions","Gain events","Gains (tip)","Loss events","Losses (tip)","Continuations of trait")

table %>% favorite_kable()

write_csv(table,"./tables/empirical/table_median_stats_across_axes.csv")
```



