---
title: "table_phenotype_genotype_synchronous_transition_summary"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr) 
opts_knit$set(echo = FALSE,warning = FALSE, message = FALSE,error=FALSE,comment=NA) 
opts_chunk$set(echo = FALSE,warning = FALSE, message = FALSE,error=FALSE,comment=NA) 
knitr::opts_knit$set(root.dir = '~/Desktop/gl_mount/Analysis/Phyloaware/joint-uncertainty-ms/') 
```

```{r environment, echo=T, message=FALSE, include=T, results=T}
#Packages
packages <- c("tidyverse",'corHMM','phyloAMR','gontjesr','kableExtra') 

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Source functions
source("./lib/consistent_themes.R")

# Print environment
set.seed(0104) 
Sys.info()
sessionInfo()
```

# Load data
## Dataset
```{r} 
dat <- readRDS("./data/empirical/dataset/df.RDS")
phy <- read.tree("./data/empirical/tree/tree.treefile") 
dbres <- readRDS("./data/empirical/joint_reconstruction/joint_uncertainty_asr_clustering_optimal.RDS")
```

## Genotype phenotype data
```{r}
synchronous_statistics <- readRDS("./data/empirical/phyloAMR/pairwise_synchronous_transitions_genotype_as_comparitor.RDS") %>% subset(!genotype %in% c("AA018","AcrAB_TolC_any","OmpK36GD","OmpK36TD","PBP2","PBP4","OmpK36_truncation_kleborate","OmpK36_putative_function_altering"))

synchronous_statistics$genotype <- factor(
synchronous_statistics$genotype,levels = c("AA552","OmpK36_c25t","OmpK36_L3_mutations","OmpK36_promoter_IS","OmpK36_disruptive","PBP_any","RamR","RamA"))

synchronous_statistics$genotype <- recode(synchronous_statistics$genotype , 'OmpK35-25'='ompK35 porin truncation at 25%','OmpK36_c25t'='25 cytosine-to-thymine transition in ompK36','OmpK36_L3_mutations'='Loop 3 insertion in ompK36','OmpK36GD'='GD loop 3 insertion in ompK36','OmpK36TD'='TD loop 3 insertion in ompK36','OmpK36_truncation_kleborate'='ompK36 truncation', 'OmpK36_non_syn'='ompK36 non-synonymous mutation','OmpK36_putative_function_altering'='ompK36 PFAV','OmpK36_intergenic'='Mutation in intergenic region of ompK36','OmpK36_promoter_IS'='Insertion seqeunce at ompK36 promoter',"AcrAB_TolC_any" = 'acrAB-tolC efflux pump mutant','RamR'='ramR efflux pump regulator PFAV',"RamA"='ramA efflux pump activator PFAV','PBP_any'='Penicillin-binding-protein mutant','PBP2'='Penicillin-binding protein-2 mutant',"PBP4"='Penicillin-binding protein-4 mutant',"AA018" = "AA018 blaKPC-containing plasmid","AA552" = "AA552 blaKPC-containing plasmid","OmpK36_disruptive" = "Putative disruptive mutation in ompK36") 
synchronous_statistics <- arrange(synchronous_statistics,genotype)

dbcluster_names <- dbres$cluster %>% `names<-`(seq_len(length(.)))
synchronous_statistics$pheno_number <- sapply(synchronous_statistics$phenotype_reconstruction,FUN=function(x){
  if(grepl("alt_recon",x)){
  gsub("alt_recon_","",x)
  } else {
    x
  } 
})  

synchronous_statistics$pheno_cluster <- sapply(synchronous_statistics$pheno_number,FUN=function(x){
  if(!grepl("focal",x)){
    dbcluster_names[names(dbcluster_names) == x]
  } else {
    x
  }
})

get_median_min_max_values <- function(variable,dataset){
 variable_summary <- dataset %>%
  group_by(genotype,pheno_cluster)  %>% 
  summarise(
    median_value = median(get(variable), na.rm = TRUE),
    min_value = min(get(variable), na.rm = TRUE),
    max_value = max(get(variable), na.rm = TRUE)
  ) %>%
  mutate(
    summary_string = sprintf("%.1f (%.1f - %.1f)", median_value, min_value, max_value)
  ) %>% ungroup %>% select(pheno_cluster,genotype,summary_string) %>% `colnames<-`(c("pheno_cluster","genotype",paste0(variable))) 
 return(variable_summary)
}
variable_transitionstats  <- c("synchronous_gains_num")

transition_stats <- lapply(variable_transitionstats,get_median_min_max_values,dataset=synchronous_statistics) %>% reduce(
  .,
  ~ left_join(.x, .y, by = c("pheno_cluster","genotype"))
)

# Pivot wide, rows should be pheno cluster and the two columns per genotype are num_concordant transitions and num_discordant_transitions
transition_stats_wide <- transition_stats %>% arrange(genotype)%>% 
  pivot_wider(
    names_from = genotype,
    values_from = c(synchronous_gains_num,),
    names_glue = "{genotype}_{.value}", names_expand = TRUE,
    names_sort = FALSE 
  ) %>%  select(pheno_cluster, sort(tidyselect::peek_vars()))

transition_stats_wide$pheno_cluster <- recode(transition_stats_wide$pheno_cluster,"focal_states" ="Best joint reconstruction",
                                             "1" ="Reconstruction axis 1",
                                             "2" ="Reconstruction axis 2",
                                             "3" ="Reconstruction axis 3",
                                             "4" ="Reconstruction axis 4",
                                             "5" ="Reconstruction axis 5") 
transition_stats_wide <- transition_stats_wide %>% select(pheno_cluster,paste0(levels(transition_stats$genotype),"_synchronous_gains_num"))

colnames(transition_stats_wide) <- gsub("_synchronous_gains_num"," sychrnounous gains",colnames(transition_stats_wide)) %>% gsub("pheno_cluster","Phenotype axis",.)
```
 
# Merged table
```{r} 
transition_stats_wide %>% favorite_kable()

write_csv(transition_stats_wide,"./tables/empirical/table_phenotype_genotype_pairwise_synchronous_transitions_summary.csv")
```