---
title: "Supplemental Figure - Painted states and phylogenetic clustering"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr) 
opts_knit$set(echo = TRUE,warning = FALSE, message = FALSE,error=FALSE,comment=NA) 
opts_chunk$set(echo = TRUE,warning = FALSE, message = FALSE,error=FALSE,comment=NA) 
knitr::opts_knit$set(root.dir = '~/Desktop/gl_mount/Analysis/Phyloaware/joint-uncertainty-ms/') 
```

# Environment
```{r environment, echo=T, message=FALSE, include=T, results=T}
#Packages
packages <- c("tidyverse",'corHMM','phyloAMR','ggtree') 

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Source functions
source("./lib/consistent_themes.R")

# Print environment
set.seed(0104) 
Sys.info()
sessionInfo()
```

# Load data
## Dataset
```{r, load datasets} 
dat <- readRDS("./data/empirical/dataset/df.RDS")
phy <- read.tree("./data/empirical/tree/tree.treefile")  
```

# Phylogenetic clustering data  
```{r, load transition data}
best_joint_parent_child <- readRDS("./data/empirical/phyloAMR/representative_blbli_joint_uncertainty_parent_child_dfs.RDS")  
phyloAMR_cluster_df <- readRDS("./data/empirical/phyloAMR/representative_blbli_joint_uncertainty_asr_clustering_df.RDS")
clustering_stats <- readRDS("./data/empirical/phyloAMR/representative_blbli_joint_uncertainty_asr_clustering_statistics.RDS")
dat <- left_join(dat,phyloAMR_cluster_df)
rownames(dat) <- dat$isolate_no
```

# Tracing states on the phylogeny
```{r,fig.width=11,fig.height=11} 
n_clusters <- nrow(clustering_stats) - 1
painted_trees <- lapply(best_joint_parent_child,paint_tree_with_states,tr = phy,legend_name = "Edge-based resistance")
painted_trees_wo_legend <- lapply(painted_trees,function(x){x+theme(legend.position = "none")}) 
 
rownames(dat) <- dat$isolate_no

variables <- names(painted_trees)
painted_trees_w_cluster_calls <- lapply(variables,FUN=function(x){
  p_obj <- painted_trees[[x]]  
  p1 <- gheatmap(p_obj,data=dat  %>% select(blbli_dich_num) %>% `colnames<-`("Resistance") %>% mutate_all(as.factor),width = 0.1,colnames_position = 'top',colnames_angle=90, colnames_offset_y = 0.25, hjust = 0, color = NA) + Resistance_scale + theme(legend.key = element_rect(colour = c('black')),legend.spacing.y=unit(.025, "cm"),legend.key.height=unit(.5,'cm'),legend.box.spacing = unit(.05, "cm"),legend.key.spacing.y = unit(0.1,"cm"))
  p1.1 <- p1 + ggnewscale::new_scale_fill() 
  p2 <- gheatmap(p1.1,data=dat  %>% select(paste0(x,"_asr_cluster_renamed")) %>% `colnames<-`("Clustering"),width = 0.1,colnames_position = 'top',colnames_angle=90, colnames_offset_y = 0.25, hjust = 0, color = NA,offset=0.000025)  + cluster_scale_v + ylim(NA,512.5)  + theme(legend.key = element_rect(colour = c('black')),legend.spacing.y=unit(.125, "cm"),legend.box.spacing = unit(.05, "cm"),legend.key.size = unit(0.5,"cm"), plot.margin = unit(c(0, 0, -0.25, 0), "cm"))   
  p2
}) 

legend_fig <- cowplot::get_legend(painted_trees_w_cluster_calls[[which.max(clustering_stats$clusters)]])  %>% cowplot::plot_grid()
  
painted_trees_w_cluster_calls_wo_legends <- lapply(painted_trees_w_cluster_calls,FUN=function(x){x + theme(legend.position='none')
}) 
 
painted_trees_w_cluster_calls_wo_legends[['legend']] <- legend_fig

tracing_states_on_tree <- cowplot::plot_grid(plotlist = painted_trees_w_cluster_calls_wo_legends,nrow=3,labels =c("Best joint reconstruction",paste0("Reconstruction axis ",1:n_clusters,"    "),""),label_x = -0.25,label_size = 14)

tracing_states_on_tree
```

# Save
```{r, save}
ggsave("./figures/empirical/ancestral_states_on_phylogeny.png",dpi = 900, bg = 'white',plot = tracing_states_on_tree,width=11,height=11)
```
