---
title: "Pairwise comparisons as boxplot"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr) 
opts_knit$set(echo = FALSE,warning = FALSE, message = FALSE,error=FALSE,comment=NA) 
opts_chunk$set(echo = FALSE,warning = FALSE, message = FALSE,error=FALSE,comment=NA) 
knitr::opts_knit$set(root.dir = '~/Desktop/gl_mount/Analysis/Phyloaware/joint-uncertainty-ms/') 
```

```{r environment, echo=T, message=FALSE, include=T, results=T}
#Packages
packages <- c("tidyverse",'corHMM','proxy','dbscan','Rtsne','phyloAMR','kableExtra') 

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Print environment
set.seed(0104) 
Sys.info()
sessionInfo()
```
 
# Load data
```{r}  
phy <- ape::read.tree("./data/empirical/tree/tree.treefile")
dat <- readRDS("./data/empirical/dataset/df.RDS")
dat <- dat[match(phy$tip.label, dat[['isolate_no']]), ]
dbres <- readRDS("./data/empirical/joint_reconstruction/joint_uncertainty_asr_clustering_optimal.RDS")
```

```{r}
genotypes <- readRDS("./data/empirical/resistance_genotypes/resistance_genotypes.RDS") 
genotypes <-  genotypes %>% .[match(phy$tip.label,.[['isolate_no']]),]

df <- left_join(dat,genotypes)
```

# Reconsctructions
```{r}
focals <- readRDS("./data/empirical/joint_reconstruction/phenotype_genotype_focal_asrs.RDS")
joint_uncs <- readRDS("./data/empirical/joint_reconstruction/phenotype_genotype_joint_uncertainty_asrs.RDS")
parent_child_dfs <- readRDS("./data/empirical/phyloAMR/joint_states_parent_child_dfs.RDS")
```

# Pairwise phyloAMR data
```{r}
pairwise_comparisons <- readRDS("./data/empirical/phyloAMR/pairwise_synchronous_transitions_genotype_as_comparitor.RDS") %>% subset(!genotype %in% c("AA018","AcrAB_TolC_any","OmpK36GD","OmpK36TD","PBP2","PBP4","OmpK36_truncation_kleborate","OmpK36_putative_function_altering"))
pairwise_comps_sync_all_geno <- readRDS("./data/empirical/phyloAMR/pairwise_synchronous_transitions_phenotype_as_comparitor.RDS") %>% subset(!genotype %in% c("AA018","AcrAB_TolC_any","OmpK36GD","OmpK36TD","PBP2","PBP4","OmpK36_truncation_kleborate","OmpK36_putative_function_altering"))
```

## Recode genotypes
## Comparison pheno
```{r}
overall_row <- cbind.data.frame(pheno_cluster = NA,genotype="Overall")
pairwise_comparisons <- bind_rows(pairwise_comparisons,overall_row)
pairwise_comparisons$genotype <- factor(
pairwise_comparisons$genotype,levels = rev(c("Overall","AA552","OmpK36_c25t","OmpK36_L3_mutations","OmpK36_promoter_IS","OmpK36_disruptive","PBP_any","RamR","RamA")))

 
pairwise_comparisons$genotype <- recode(pairwise_comparisons$genotype , 'OmpK35-25'='ompK35 porin truncation at 25%','OmpK36_c25t'='25 cytosine-to-thymine transition in ompK36','OmpK36_L3_mutations'='Loop 3 insertion in ompK36','OmpK36GD'='GD loop 3 insertion in ompK36','OmpK36TD'='TD loop 3 insertion in ompK36','OmpK36_truncation_kleborate'='ompK36 truncation', 'OmpK36_non_syn'='ompK36 non-synonymous mutation','OmpK36_putative_function_altering'='ompK36 PFAV','OmpK36_intergenic'='Mutation in intergenic region of ompK36','OmpK36_promoter_IS'='Insertion seqeunce at ompK36 promoter',"AcrAB_TolC_any" = 'acrAB-tolC efflux pump mutant','RamR'='ramR efflux pump regulator PFAV',"RamA"='ramA efflux pump activator PFAV','PBP_any'='Penicillin-binding-protein mutant','PBP2'='Penicillin-binding protein-2 mutant',"PBP4"='Penicillin-binding protein-4 mutant',"AA018" = "AA018 blaKPC-containing plasmid","AA552" = "AA552 blaKPC-containing plasmid","OmpK36_disruptive" = "Putative disruptive mutation in ompK36") 

pairwise_comparisons$pheno_cluster <- recode(pairwise_comparisons$pheno_cluster,"focal_states" ="Best joint reconstruction",
                                             "1" ="Reconstruction axis 1",
                                             "2" ="Reconstruction axis 2",
                                             "3" ="Reconstruction axis 3",
                                             "4" ="Reconstruction axis 4",
                                             "5" ="Reconstruction axis 5") 
```
## Comparison genotype
```{r}
pairwise_comps_sync_all_geno <- bind_rows(pairwise_comps_sync_all_geno,overall_row)
pairwise_comps_sync_all_geno$genotype <- factor(
pairwise_comps_sync_all_geno$genotype,levels = rev(c("Overall","AA552","OmpK36_c25t","OmpK36_L3_mutations","OmpK36_promoter_IS","OmpK36_disruptive","PBP_any","RamR","RamA")))
 
pairwise_comps_sync_all_geno$genotype <- recode(pairwise_comps_sync_all_geno$genotype , 'OmpK35-25'='ompK35 porin truncation at 25%','OmpK36_c25t'='25 cytosine-to-thymine transition in ompK36','OmpK36_L3_mutations'='Loop 3 insertion in ompK36','OmpK36GD'='GD loop 3 insertion in ompK36','OmpK36TD'='TD loop 3 insertion in ompK36','OmpK36_truncation_kleborate'='ompK36 truncation', 'OmpK36_non_syn'='ompK36 non-synonymous mutation','OmpK36_putative_function_altering'='ompK36 PFAV','OmpK36_intergenic'='Mutation in intergenic region of ompK36','OmpK36_promoter_IS'='Insertion seqeunce at ompK36 promoter',"AcrAB_TolC_any" = 'acrAB-tolC efflux pump mutant','RamR'='ramR efflux pump regulator PFAV',"RamA"='ramA efflux pump activator PFAV','PBP_any'='Penicillin-binding-protein mutant','PBP2'='Penicillin-binding protein-2 mutant',"PBP4"='Penicillin-binding protein-4 mutant',"AA018" = "AA018 blaKPC-containing plasmid","AA552" = "AA552 blaKPC-containing plasmid","OmpK36_disruptive" = "Putative disruptive mutation in ompK36") 

pairwise_comps_sync_all_geno$pheno_cluster <- recode(pairwise_comps_sync_all_geno$pheno_cluster,"focal_states" ="Best joint reconstruction",
                                             "1" ="Reconstruction axis 1",
                                             "2" ="Reconstruction axis 2",
                                             "3" ="Reconstruction axis 3",
                                             "4" ="Reconstruction axis 4",
                                             "5" ="Reconstruction axis 5") 
```

# Overall summary figures 
## A. Concordant synchronous transitions
```{r,fig.width=9,fig.height=9}
A <- ggplot(pairwise_comparisons,
       aes(x = synchronous_gains_num,
           y = as.factor(genotype),
           fill = as.factor(pheno_cluster))) +
geom_boxplot(position = position_dodge(width = 0.8)) +
labs(x = "Synchronous phenotype-genotype gain events",
     y = "",
     fill = "Phenotype axes") +
scale_fill_brewer(palette = "Set1",guide = guide_legend(nrow=1)) +
theme(axis.text.x = element_text(angle = 45, hjust = 1)) + theme_bw() + scale_x_continuous(breaks = c(0,2,4,6,8,10)) + xlim(NA,10.1) + theme(legend.position = 'bottom')

A
```
 
# Get proportion of genotypes with gain event of phenotype
```{r,fig.width=9,fig.height=7.5} 
B <- ggplot(pairwise_comps_sync_all_geno,
       aes(x = synchronous_gains_prop,
           y = as.factor(genotype),
           fill = as.factor(pheno_cluster))) +
geom_boxplot(position = position_dodge(width = 0.8)) +
labs(x = "Proportion of genotype gains with a phenotype gain",
     y = "",
     fill = "Phenotype axes") +
scale_fill_brewer(palette = "Set1",guide = guide_legend(nrow=1)) +
theme(axis.text.x = element_text(angle = 45, hjust = 1)) + theme_bw() + theme(legend.position = 'bottom')

B
```

# Proportion of phenotype gains with >=1 genotype gain
```{r,fig.width=9,fig.height=7.5} 
pheno_recons <- pairwise_comparisons$phenotype_reconstruction %>% unique %>% sort()
genotypes <-  names(parent_child_dfs) %>% subset(.!='blbli_dich_num') %>% sort %>% subset(. %in% c("AA552","OmpK36_c25t","OmpK36_L3_mutations","OmpK36_promoter_IS","OmpK36_disruptive","PBP_any","RamR","RamA"))

pheno_gain_explanation <- pbmcapply::pbmclapply(pheno_recons,FUN=function(x){
  pheno_recon_pcdf <- parent_child_dfs$blbli_dich_num[[x]]
  pheno_recon_gains <- subset(pheno_recon_pcdf,gain==1) %>% .$child %>% as.numeric() %>% sort
  num_pheno_gain <- length(pheno_recon_gains)
  genotype_pheno_data <- lapply(genotypes,FUN=function(geno){
    geno_recon_pcdfs <- parent_child_dfs[[geno]]
    geno_recon_gains <- lapply(geno_recon_pcdfs,FUN=function(genopcdf){
       subset(genopcdf,gain==1) %>% .$child
    }) %>% unlist %>% unique %>% sort
    num_nodes_w_geno_gains <- length(geno_recon_gains)
    pheno_gain_nodes_w_geno_gains <- pheno_recon_gains %>% subset(. %in% geno_recon_gains)
    num_pheno_gain_nodes_w_geno_gains <- length(pheno_gain_nodes_w_geno_gains)
    prop_pheno_gains_w_geno_gain <- num_pheno_gain_nodes_w_geno_gains /     num_pheno_gain
    perc_pheno_gains_w_geno_gain <- prop_pheno_gains_w_geno_gain*100
    data.frame(genotype = geno,pheno_reconstruction = x,pheno_recon_gains = paste0(pheno_recon_gains,collapse = ','),num_pheno_gain,geno_recon_gains = paste0(geno_recon_gains,collapse=','),num_nodes_w_geno_gains,prop_pheno_gains_w_geno_gain,perc_pheno_gains_w_geno_gain)
    
  }) %>% do.call(rbind,.)
},mc.cores = 7)

pheno_gain_explanation_df <- do.call(rbind,pheno_gain_explanation) 

# Add overall row
overall_row <- pbmcapply::pbmclapply(pheno_recons,FUN=function(x){
  pheno_recon_pcdf <- parent_child_dfs$blbli_dich_num[[x]]
  pheno_recon_gains <- subset(pheno_recon_pcdf,gain==1) %>% .$child %>% as.numeric() %>% sort
  num_pheno_gain <- length(pheno_recon_gains)
  geno_recon_pcdfs <- subset(parent_child_dfs,names(parent_child_dfs) != 'blbli_dich_num')
  
  geno_recon_gains <- lapply(geno_recon_pcdfs,FUN=function(y){
    lapply(y,FUN=function(genopcdf){
       subset(genopcdf,gain==1) %>% .$child
    })}) %>% unlist %>% unique %>% sort
   
    num_nodes_w_geno_gains <- length(geno_recon_gains)
    pheno_gain_nodes_w_geno_gains <- pheno_recon_gains %>% subset(. %in% geno_recon_gains)
    num_pheno_gain_nodes_w_geno_gains <- length(pheno_gain_nodes_w_geno_gains)
    prop_pheno_gains_w_geno_gain <- num_pheno_gain_nodes_w_geno_gains /     num_pheno_gain
    perc_pheno_gains_w_geno_gain <- prop_pheno_gains_w_geno_gain*100
    data.frame(genotype = "Overall",pheno_reconstruction = x,pheno_recon_gains = paste0(pheno_recon_gains,collapse = ','),num_pheno_gain,geno_recon_gains = paste0(geno_recon_gains,collapse=','),num_nodes_w_geno_gains,prop_pheno_gains_w_geno_gain,perc_pheno_gains_w_geno_gain)
  },mc.cores = 7) %>% do.call(rbind,.) 

pheno_gain_explanation_df <- rbind(pheno_gain_explanation_df,overall_row)

# Organize
pheno_gain_explanation_df$genotype <- factor(
pheno_gain_explanation_df$genotype,levels = rev(c("Overall","AA552","OmpK36_c25t","OmpK36_L3_mutations","OmpK36_promoter_IS","OmpK36_disruptive","PBP_any","RamR","RamA")))

pheno_gain_explanation_df$genotype <- recode(pheno_gain_explanation_df$genotype , 'OmpK35-25'='ompK35 porin truncation at 25%','OmpK36_c25t'='25 cytosine-to-thymine transition in ompK36','OmpK36_L3_mutations'='Loop 3 insertion in ompK36','OmpK36GD'='GD loop 3 insertion in ompK36','OmpK36TD'='TD loop 3 insertion in ompK36','OmpK36_truncation_kleborate'='ompK36 truncation', 'OmpK36_non_syn'='ompK36 non-synonymous mutation','OmpK36_putative_function_altering'='ompK36 PFAV','OmpK36_intergenic'='Mutation in intergenic region of ompK36','OmpK36_promoter_IS'='Insertion seqeunce at ompK36 promoter',"AcrAB_TolC_any" = 'acrAB-tolC efflux pump mutant','RamR'='ramR efflux pump regulator PFAV',"RamA"='ramA efflux pump activator PFAV','PBP_any'='Penicillin-binding-protein mutant','PBP2'='Penicillin-binding protein-2 mutant',"PBP4"='Penicillin-binding protein-4 mutant',"AA018" = "AA018 blaKPC-containing plasmid","AA552" = "AA552 blaKPC-containing plasmid","OmpK36_disruptive" = "Putative disruptive mutation in ompK36") 

pheno_gain_explanation_df$pheno_number <- sapply(pheno_gain_explanation_df$pheno_reconstruction,FUN=function(x){
  if(grepl("alt_recon",x)){
    
  gsub("alt_recon_","",x)
  } else {
    x
  } 
})  

dbcluster_names <- dbres$cluster %>% `names<-`(seq_len(length(.)))

pheno_gain_explanation_df$pheno_cluster <- sapply(pheno_gain_explanation_df$pheno_number,FUN=function(x){
  if(!grepl("focal",x)){
    dbcluster_names[names(dbcluster_names) == x]
  } else {
    x
  }
})

pheno_gain_explanation_df$pheno_cluster <- recode(pheno_gain_explanation_df$pheno_cluster,"focal_states" ="Best joint reconstruction",
                                             "1" ="Reconstruction axis 1",
                                             "2" ="Reconstruction axis 2",
                                             "3" ="Reconstruction axis 3",
                                             "4" ="Reconstruction axis 4",
                                             "5" ="Reconstruction axis 5") 

C<- ggplot(pheno_gain_explanation_df,
       aes(x = prop_pheno_gains_w_geno_gain,
           y = as.factor(genotype),
           fill = as.factor(pheno_cluster))) +
geom_boxplot(position = position_dodge(width = 0.8)) +
labs(x = "Proportion of phenotype gains with >=1 genotype gain",
     y = "",
     fill = "Phenotype axes") +
scale_fill_brewer(palette = "Set1",guide = guide_legend(nrow=1)) +
theme(axis.text.x = element_text(angle = 45, hjust = 1)) + theme_bw() + theme(legend.position = 'bottom') + xlim(NA,0.601)  + scale_x_continuous(breaks = c(0,0.1,0.20,0.3,0.4,0.5,0.6))

C
```
# Merged
```{r,fig.width=15.5 ,fig.height=6.5}
library(patchwork)

# Define a single, consistent legend title.
legend_title <- ""

# Apply the same title to all plots and specify a horizontal layout for the legend.
# Patchwork will use this structure when it collects the guides.
A <- A + labs(fill = legend_title) + guides(fill = guide_legend(nrow = 1))
B <- B + labs(fill = legend_title) + guides(fill = guide_legend(nrow = 1))
C <- C + labs(fill = legend_title) + guides(fill = guide_legend(nrow = 1))

# 1. Create a dedicated y-axis plot (this part is now correct).
y_axis_plot <- ggplot(A$data, aes(y = !!A$mapping$y)) +
  theme_void() +
  theme(
    axis.text.y = element_text(
      size = 11, # Match font size to your main plot
      hjust = 1, # Right-align the text
      colour = "black"
    ),
    # The right margin on the plot now solely controls the gap
    plot.margin = margin(0, 5, 0, 0) # Units are in 'pt'
  )

# 2. Modify plots A, B, and C to remove their y-axes and legends.
A_main <- A + labs(tag = "A") +
  theme(axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        legend.position = "none")

B_main <- B + labs(tag = "B") +
  theme(axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        legend.position = "none")

C_main <- C + labs(tag = "C") +
  theme(axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        legend.position = "none")


# 3. Assemble the final figure with patchwork.
figure <- y_axis_plot + A_main + B_main + C_main +
  plot_layout(
    guides = 'collect', # This will now find one single, standardized legend
    # --- KEY FIX 2: Adjust Relative Widths ---
    # Reduce the first value to shrink the space for the y-axis labels.
    # A value of 0.3 or less is likely what you need. Adjust as necessary.
    widths = c(0.01, 1, 1, 1),
  ) &
  # Position the single, collected legend at the bottom.
  theme(legend.position = 'bottom',legend.title = element_text(size=14),legend.text = element_text(size=11.75))

figure
ggsave("./figures/empirical/pairwise_reconstruction_synchronous_transition_comparisons_boxplot.png",
       dpi = 900,
       bg = 'white',
       plot = figure,
       width = 15.5,
       height = 6.5)
```
