---
title: "phyloAMR permutation testing"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr) 
opts_knit$set(echo = FALSE,warning = FALSE, message = FALSE,error=FALSE,comment=NA) 
opts_chunk$set(echo = FALSE,warning = FALSE, message = FALSE,error=FALSE,comment=NA) 
knitr::opts_knit$set(root.dir = '~/Desktop/gl_mount/Analysis/Phyloaware/joint-uncertainty-ms/') 
```

```{r environment, echo=T, message=FALSE, include=T, results=T}
#Packages
packages <- c("tidyverse",'corHMM','phyloAMR') 

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Source functions
source("./lib/consistent_themes.R")

# Print environment
set.seed(0104) 
Sys.info()
sessionInfo()
```

# Load data
## Dataset
```{r} 
dat <- readRDS("./data/empirical/dataset/df.RDS")
phy <- read.tree("./data/empirical/tree/tree.treefile") 
genotypes <- readRDS("./data/empirical/resistance_genotypes/resistance_genotypes.RDS") 
```

# Transition data
```{r}
permutation_results <- readRDS("./data/empirical/phyloAMR/phenotype_genotype_transition_association_statistics.RDS")

```

```{r}
synchronous_pvalue_results <- lapply(permutation_results$synchronous_permutations,FUN=function(x){
  lapply(x,FUN=function(y){y[['results_df']]}) %>% do.call(rbind.data.frame,.) %>% mutate(comparitor = names(x))
}) 

synchronous_pvalue_results_df <- lapply(names(synchronous_pvalue_results),FUN=function(x){
  synchronous_pvalue_results[[x]] %>% mutate(phenotype_axis = x) 
}) %>% do.call(rbind,.)


downstream_pvalue_results <- lapply(permutation_results$downstream_permutations,FUN=function(x){
  lapply(x,FUN=function(y){y[['results_df']]}) %>% do.call(rbind.data.frame,.) %>% mutate(comparitor = names(x))
}) 

downstream_pvalue_results_df <- lapply(names(downstream_pvalue_results),FUN=function(x){
  downstream_pvalue_results[[x]] %>% mutate(phenotype_axis = x) 
}) %>% do.call(rbind,.)
```
 

# Synchronous p-values 
```{r,fig.height=16.5,fig.width=12.5}

synchronous_pvalue_results_df$comparitor <- factor(
synchronous_pvalue_results_df$comparitor,levels = c("AA018","AA552","OmpK36_c25t","OmpK36GD","OmpK36TD","OmpK36_promoter_IS","OmpK36_truncation_kleborate","OmpK36_putative_function_altering","PBP2","PBP4","AcrAB_TolC_any","RamR","RamA"))

synchronous_pvalue_results_df$comparitor <- recode(synchronous_pvalue_results_df$comparitor ,'OmpK35-25'='ompK35 porin truncation at 25%','OmpK36_c25t'='25 cytosine-to-thymine transition in ompK36','OmpK36_L3_mutations'='Loop 3 insertion in ompK36','OmpK36GD'='GD loop 3 insertion','OmpK36TD'='TD loop 3 insertion','OmpK36_truncation_kleborate'='ompK36 truncation', 'OmpK36_non_syn'='ompK36 non-synonymous mutation','OmpK36_putative_function_altering'='ompK36 PFAV','OmpK36_intergenic'='Mutation in intergenic region of ompK36','OmpK36_promoter_IS'='Insertion seqeunce at ompK36 promoter',"AcrAB_TolC_any" = 'acrAB-tolC efflux pump mutant','RamR'='ramR efflux pump regulator PFAV',"RamA"='ramA efflux pump activator PFAV','PBP_any'='Non-synonymous mutations in penicillin-binding-proteins','PBP2'='Penicillin-binding protein-2 mutant',"PBP4"='Penicillin-binding protein-4 mutant',"AA018" = "AA018 blaKPC-containing plasmid","AA552" = "AA551 blaKPC-containing plasmid") 

synchronous_pvalue_results_df$phenotype_axis <- recode(synchronous_pvalue_results_df$phenotype_axis,"best_joint" ="Best joint model",
                                             "JR_cluster_1" ="Alternative axes 1",
                                             "JR_cluster_2" ="Alternative axes 2",
                                             "JR_cluster_3" ="Alternative axes 3",
                                             "JR_cluster_4" ="Alternative axes 4",
                                             "JR_cluster_5" ="Alternative axes 5") 


axes_fill <- scale_fill_manual(breaks = c(unique(synchronous_pvalue_results_df$phenotype_axis)%>% factor),values=c("black", "#E41A1C", "#377EB8", "#4DAF4A", "#984EA3", "#FF7F00", "#FFFF33","gray"),name="Phenotype axes")

sync_variables <- c("transition_pval","synchronous_gain_pval","synchronous_loss_pval","synchronous_gain_loss_pval","synchronous_gain_loss_pval","synchronous_loss_gain_pval")

synchronous_pval_figs <- lapply(sync_variables,FUN=function(x){
  name <- recode(x,"transition_pval" = 'transition p-value',"synchronous_gain_pval" = 'synchronous gain p-value',"synchronous_loss_pval" = 'synchronous loss p-value',"synchronous_gain_loss_pval" = 'synchronous gain-loss p-value',"synchronous_gain_loss_pval" = 'synchronous gain-loss p-value',"synchronous_loss_gain_pval" = 'sychronous loss-gain p-value')
  
ggplot(data=synchronous_pvalue_results_df,aes(x=comparitor,y=-log(get(x)),group=as.factor(phenotype_axis),fill=as.factor(phenotype_axis))) + geom_bar(position="dodge",stat='identity') + axes_fill + theme_bw() + ylab(name) + xlab("Comparitor") + ylim(NA,6.5) + theme(axis.text.x = element_text(angle=90)) + geom_hline(yintercept = -log(0.1),linetype = 2)   + geom_hline(yintercept = -log(0.05),colour = 'red',linetype = 2)
})

synchronous_pvalue_plots <- cowplot::plot_grid(plotlist = synchronous_pval_figs,ncol=2,labels = "AUTO")

synchronous_pvalue_plots

ggsave("./figures/empirical/phyloAMR_synchronous_permutation_test_pvalues.png",dpi = 900,bg = 'white',plot = synchronous_pvalue_plots,width=12.5,height=17.5) 
```

# Downstream p-values 

```{r,fig.height=19,fig.width=12.5} 

downstream_pvalue_results_df$comparitor <- factor(
downstream_pvalue_results_df$comparitor,levels = c("AA018","AA552","OmpK36_c25t","OmpK36GD","OmpK36TD","OmpK36_promoter_IS","OmpK36_truncation_kleborate","OmpK36_putative_function_altering","PBP2","PBP4","AcrAB_TolC_any","RamR","RamA"))

downstream_pvalue_results_df$comparitor <- recode(downstream_pvalue_results_df$comparitor ,'OmpK35-25'='ompK35 porin truncation at 25%','OmpK36_c25t'='25 cytosine-to-thymine transition in ompK36','OmpK36_L3_mutations'='Loop 3 insertion in ompK36','OmpK36GD'='GD loop 3 insertion','OmpK36TD'='TD loop 3 insertion','OmpK36_truncation_kleborate'='ompK36 truncation', 'OmpK36_non_syn'='ompK36 non-synonymous mutation','OmpK36_putative_function_altering'='ompK36 PFAV','OmpK36_intergenic'='Mutation in intergenic region of ompK36','OmpK36_promoter_IS'='Insertion seqeunce at ompK36 promoter',"AcrAB_TolC_any" = 'acrAB-tolC efflux pump mutant','RamR'='ramR efflux pump regulator PFAV',"RamA"='ramA efflux pump activator PFAV','PBP_any'='Non-synonymous mutations in penicillin-binding-proteins','PBP2'='Penicillin-binding protein-2 mutant',"PBP4"='Penicillin-binding protein-4 mutant',"AA018" = "AA018 blaKPC-containing plasmid","AA552" = "AA551 blaKPC-containing plasmid") 


downstream_pvalue_results_df$phenotype_axis <- recode(downstream_pvalue_results_df$phenotype_axis,"best_joint" ="Best joint model",
                                             "JR_cluster_1" ="Alternative axes 1",
                                             "JR_cluster_2" ="Alternative axes 2",
                                             "JR_cluster_3" ="Alternative axes 3",
                                             "JR_cluster_4" ="Alternative axes 4",
                                             "JR_cluster_5" ="Alternative axes 5") 

downstream_variables <-colnames(downstream_pvalue_results_df) %>% subset(!.%in% c('comparitor','phenotype_axis'))

downstream_pval_figs <- lapply(downstream_variables,FUN=function(x){
  name <- recode(x,"downstream_transition_pval"    ="Downstream transitions p-value","downstream_transition_stretches_pval" = "Downstream strecthes count p-value", "downstream_gain_pval"= "Downstream gains p-value","downstream_gains_stretches_pval"  = "Downstream gain stretches count p-value",   "downstream_loss_pval" = "Downstream losses p-value", "downstream_loss_stretches_pval"   = "Downstream loss stretches count p-value")
  
ggplot(data=downstream_pvalue_results_df,aes(x=comparitor,y=-log(get(x)),group=as.factor(phenotype_axis),fill=as.factor(phenotype_axis))) + geom_bar(position="dodge",stat='identity') + axes_fill   + theme_bw() + ylab(name) + xlab("Comparitor") + ylim(NA,6.5) + theme(axis.text.x = element_text(angle=90)) + geom_hline(yintercept = -log(0.1),linetype = 2)   + geom_hline(yintercept = -log(0.05),colour = 'red',linetype = 2)
})

downstream_pvalue_plots <- cowplot::plot_grid(plotlist = downstream_pval_figs,ncol=2,labels = "AUTO")

downstream_pvalue_plots

ggsave("./figures/empirical/phyloAMR_downstream_permutation_test_pvalues.png",dpi = 900,bg = 'white',plot = downstream_pvalue_plots,width=12.5,height=19) 
```
