---
title: "Supplementary Figure - Transition statistics for representative recons from the axes"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE}
require(knitr) 
opts_knit$set(echo = FALSE,warning = FALSE, message = FALSE,error=FALSE,comment=NA) 
opts_chunk$set(echo = FALSE,warning = FALSE, message = FALSE,error=FALSE,comment=NA) 
knitr::opts_knit$set(root.dir = '~/Desktop/gl_mount/Analysis/Phyloaware/joint-uncertainty-ms/') 
```

```{r environment, echo=T, message=FALSE, include=T, results=T}
#Packages
packages <- c("tidyverse",'corHMM','phyloAMR','ggtree') 

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Source functions
source("./lib/consistent_themes.R")

# Print environment
set.seed(0104) 
Sys.info()
sessionInfo()
```

# Load data
## Dataset

# Transition data
```{r} 
synchronous_df <- readRDS("./data/empirical/phyloAMR/representative_phenotype_genotype_synchronous_transition_statistics.RDS")%>% subset(genotype %in% c("AA552","OmpK36_c25t","OmpK36_L3_mutations","OmpK36_promoter_IS","OmpK36_disruptive","PBP_any","RamR","RamA"))
downstream_df <- readRDS("./data/empirical/phyloAMR/representative_phenotype_genotype_downstream_transition_statistics.RDS") %>% subset(genotype %in% c("AA552","OmpK36_c25t","OmpK36_L3_mutations","OmpK36_promoter_IS","OmpK36_disruptive","PBP_any","RamR","RamA"))
```

# Edit
## Synchronous
```{r}
synchronous_df$genotype <- factor(
synchronous_df$genotype,levels = c("AA552","OmpK36_c25t","OmpK36_L3_mutations","OmpK36_promoter_IS","OmpK36_disruptive","PBP_any","RamR","RamA"))

synchronous_df$genotype <- recode(synchronous_df$genotype  , 'OmpK35-25'='ompK35 porin truncation at 25%','OmpK36_c25t'='25 cytosine-to-thymine transition in ompK36','OmpK36_L3_mutations'='Loop 3 insertion in ompK36','OmpK36GD'='GD loop 3 insertion in ompK36','OmpK36TD'='TD loop 3 insertion in ompK36','OmpK36_truncation_kleborate'='ompK36 truncation', 'OmpK36_non_syn'='ompK36 non-synonymous mutation','OmpK36_putative_function_altering'='ompK36 PFAV','OmpK36_intergenic'='Mutation in intergenic region of ompK36','OmpK36_promoter_IS'='Insertion sequence at ompK36 promoter',"AcrAB_TolC_any" = 'acrAB-tolC efflux pump mutant','RamR'='PFAV in ramR efflux pump regulator',"RamA"='PFAV in ramA efflux pump activator','PBP_any'='Penicillin-binding-protein mutant','PBP2'='Penicillin-binding protein-2 mutant',"PBP4"='Penicillin-binding protein-4 mutant',"AA018" = "AA018 blaKPC-containing plasmid","AA552" = "AA552 blaKPC-containing plasmid","OmpK36_disruptive" = "PFAV in ompK36") 

synchronous_df$phenotype_axis <- recode(synchronous_df$phenotype_axis,"best_joint" ="Best joint reconstruction",
                                             "JR_cluster_1" ="Reconstruction axis 1",
                                             "JR_cluster_2" ="Reconstruction axis 2",
                                             "JR_cluster_3" ="Reconstruction axis 3",
                                             "JR_cluster_4" ="Reconstruction axis 4",
                                             "JR_cluster_5" ="Reconstruction axis 5") 
```

## Downstream
```{r}
downstream_df$genotype <- factor(
downstream_df$genotype,levels = c("AA552","OmpK36_c25t","OmpK36_L3_mutations","OmpK36_promoter_IS","OmpK36_disruptive","PBP_any","RamR","RamA"))

downstream_df$genotype <- recode(downstream_df$genotype , 'OmpK35-25'='ompK35 porin truncation at 25%','OmpK36_c25t'='25 cytosine-to-thymine transition in ompK36','OmpK36_L3_mutations'='Loop 3 insertion in ompK36','OmpK36GD'='GD loop 3 insertion in ompK36','OmpK36TD'='TD loop 3 insertion in ompK36','OmpK36_truncation_kleborate'='ompK36 truncation', 'OmpK36_non_syn'='ompK36 non-synonymous mutation','OmpK36_putative_function_altering'='ompK36 PFAV','OmpK36_intergenic'='Mutation in intergenic region of ompK36','OmpK36_promoter_IS'='Insertion sequence at ompK36 promoter',"AcrAB_TolC_any" = 'acrAB-tolC efflux pump mutant','RamR'='PFAV in ramR efflux pump regulator',"RamA"='PFAV in ramA efflux pump activator','PBP_any'='Penicillin-binding-protein mutant','PBP2'='Penicillin-binding protein-2 mutant',"PBP4"='Penicillin-binding protein-4 mutant',"AA018" = "AA018 blaKPC-containing plasmid","AA552" = "AA552 blaKPC-containing plasmid","OmpK36_disruptive" = "PFAV in ompK36") 

downstream_df$phenotype_axis <- recode(downstream_df$phenotype_axis,"best_joint" ="Best joint reconstruction",
                                             "JR_cluster_1" ="Reconstruction axis 1",
                                             "JR_cluster_2" ="Reconstruction axis 2",
                                             "JR_cluster_3" ="Reconstruction axis 3",
                                             "JR_cluster_4" ="Reconstruction axis 4",
                                             "JR_cluster_5" ="Reconstruction axis 5") 
```


# Figure

```{r,fig.width=15,fig.height=12}
ymax <- max(synchronous_df  %>% select(synchronous_gains_num,synchronous_gain_loss_num,synchronous_losses_num) %>% unlist %>% as.numeric)  

A <- ggplot(data=synchronous_df,aes(y=synchronous_gains_num,fill=as.factor(phenotype_axis),x=genotype)) + geom_bar(position="dodge", stat="identity") + labs(fill="Phenotype Axis") + ylab("Synchronous gains") + xlab("")+ theme_bw() + theme(legend.position="none") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + ylim(NA,ymax) + phylogenetic_reconstruction_scale

B <- ggplot(data=synchronous_df,aes(y=synchronous_gain_loss_num,fill=as.factor(phenotype_axis),x=genotype)) + geom_bar(position="dodge", stat="identity") + labs(fill="Phenotype Axis") + ylab("Phenotype gain + genotype loss") + xlab("") + theme_bw()  + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+ ylim(NA,ymax) + phylogenetic_reconstruction_scale

C <- ggplot(data=synchronous_df ,aes(y=synchronous_losses_num,fill=as.factor(phenotype_axis),x=genotype)) + geom_bar(position="dodge", stat="identity") + labs(fill="Phenotype Axis") + ylab("Synchronous losses") + xlab("")+ theme_bw()  + theme(legend.position="none") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+ ylim(NA,ymax) + phylogenetic_reconstruction_scale

D <- ggplot(data=synchronous_df,aes(y=synchronous_loss_gain_num,fill=as.factor(phenotype_axis),x=genotype)) + geom_bar(position="dodge", stat="identity") + labs(fill="Phenotype Axis") + ylab("Pphenotype loss + genotype gain") + xlab("") + theme_bw()   + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+ ylim(NA,ymax)  + phylogenetic_reconstruction_scale
  
E <- ggplot(data=downstream_df,aes(y=stretches_w_gains_num,fill=as.factor(phenotype_axis),x=genotype)) + geom_bar(position="dodge", stat="identity") + labs(fill="Phenotype Axis") + ylab("Phenotype stretches with genotype gains") + xlab("") + theme_bw() + phylogenetic_reconstruction_scale + ylim(0,ymax) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) 

figF <- ggplot(data=downstream_df,aes(y=stretches_w_losses_num,fill=as.factor(phenotype_axis),x=genotype)) + geom_bar(position="dodge", stat="identity") + labs(fill="Phenotype Axis") + ylab("Phenotype stretches with genotype losses") + xlab("")+ theme_bw()   + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + phylogenetic_reconstruction_scale + ylim(0,ymax)

legend_axes_fig <- cowplot::get_legend(D)
  
genotype_phenotype_figure <- cowplot::plot_grid(A + theme(legend.position="none"),B + theme(legend.position="none"),E+ theme(legend.position="none"),C + theme(legend.position="none"),D + theme(legend.position="none"),figF + theme(legend.position="none"),labels = c("A","B","C","D","E","F"),rel_widths = c(1,1,1,1,1,1),ncol=3)

genotype_phenotype_figure_w_legend <- cowplot::plot_grid(genotype_phenotype_figure,legend_axes_fig,ncol=2,rel_widths = c(1,0.125))

genotype_phenotype_figure_w_legend
```

```{r}
ggsave("./figures/empirical/phyloAMR_genotype_phenotype_transitions.png",dpi = 600,bg = 'white',plot = genotype_phenotype_figure_w_legend,width=15,height=12) 
```

