---
title: "Figures detailing ancestral state reconstructions"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr) 
opts_knit$set(echo = TRUE,warning = FALSE, message = FALSE,error=FALSE,comment=NA) 
opts_chunk$set(echo = TRUE,warning = FALSE, message = FALSE,error=FALSE,comment=NA) 
knitr::opts_knit$set(root.dir = '~/Desktop/gl_mount/Analysis/Phyloaware/joint-uncertainty-ms/') 
```

# Environment

```{r environment, echo=T, message=FALSE, include=T, results=T} 
#Packages
packages <- c("tidyverse",'corHMM','proxy','dbscan','phyloAMR') 

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Source functions
source("./lib/consistent_themes.R")

# Print environment
set.seed(0104) 
Sys.info()
sessionInfo()
```

# Load data
## Dataset and phylogeny
```{r load tree df}   
phy <- ape::read.tree("./data/empirical/tree/tree.treefile")
dat <- readRDS("./data/empirical/dataset/df.RDS")
dat <- dat[match(phy$tip.label, dat[['isolate_no']]), ]
```

## Ancestral states
```{r load recon data} 
focal <- readRDS("./data/empirical/joint_reconstruction/phenotype_genotype_focal_asrs.RDS") %>% .[["blbli_dich_num"]]
joint_ci <- readRDS("./data/empirical/joint_reconstruction/phenotype_genotype_joint_uncertainty_asrs.RDS")%>% .[["blbli_dich_num"]]

state_df <- joint_ci$state_df
state_df_matrix <- as.matrix(state_df)
  
clustering_7 <- readRDS("./data/empirical/joint_reconstruction/hclust_consensus_distance_matrix_seven_clusters_string.RDS") 
hclust_obj <- readRDS("./data/empirical/joint_reconstruction/hclust_consensus_distance_matrix.RDS") 

dist_mat <- readRDS("./data/empirical/joint_reconstruction/joint_uncertainty_asr_phylo_dist_matrix.RDS")
```

## Chosen cluster assignments & theme
```{r}
# Cluster assignments
cluster_assignments <- clustering_7
clusters <- factor(cluster_assignments) 
optimal_k_gap <- sum(as.numeric(unique(cluster_assignments)) >0)

# Cluster colors
clust_cols <- phylogenetic_reconstruction_scale$palette(length(phylogenetic_reconstruction_scale$breaks))[1+1:sum(levels(clusters) !=0)]
```

# Phylogeny with node states
```{r phylo w node states} 
pdf("./figures/empirical/empirical_phylogeny.pdf", height = 5.667, width = 17)   
to_keep <- corHMM:::get_desc(phy, 417)
to_col <- match(to_keep, phy$edge[,2])
edge_col <- rep("grey60", dim(phy$edge)[1])
edge_col[to_col] <- "black"
nodes_to_col <- to_keep[to_keep > Ntip(phy)] 
nodes_number <- as.numeric(to_keep[to_keep > Ntip(phy)]  - Ntip(phy))  %>% sort
tips_to_keep <- as.numeric(to_keep[to_keep <= Ntip(phy)]) %>% sort

plot(phy, show.tip.label = FALSE, no.margin = TRUE, direction = "downwards", edge.color = edge_col)

nodelabels(pch = 21,  cex = 0.75, bg = c("white", "grey70")[joint_ci$best_joint$lik.anc.states], col = "grey70") 
tiplabels(pch = 22,  cex = 0.5, bg = c("white", "grey70")[joint_ci$best_joint$lik.tip.states], col = "grey70",tip = c(1:Ntip(phy)))  
nodelabels(pch = 21,  cex = 0.75, bg = c("white", "black")[joint_ci$best_joint$lik.anc.states][nodes_number], col = "black",node = sort(nodes_to_col))
tiplabels(pch = 22,  cex = 0.5, bg = c("white", "black")[joint_ci$best_joint$lik.tip.states][tips_to_keep], col = "black",tip = c(1:Ntip(phy))[tips_to_keep])  

dev.off()
```

# Raw ancestral reconstruction figure
```{r raw ancestral recon figure}  
pdf("./figures/empirical/empirical_joint_uncertainty_reconstructions.pdf", height = 15, width = 5.5)
par(mar=c(0,0,0,0))
m <- t(state_df_matrix)[, order(cluster_assignments)]
m <- m[, ncol(m):1]
colors <- ifelse(m == 2, "black", "white")
color_matrix <- matrix(colors, nrow = nrow(m), ncol = ncol(m))
plot(1, type="n", xlim=c(1, nrow(m)), ylim=c(1, ncol(m)), axes = FALSE, xlab = "", ylab = "")
for (i in 1:nrow(m)) {
  for (j in 1:ncol(m)) {
    if(color_matrix[i, j] == "white"){
      next
    }else{
      rect(i - 0.5, j - 0.5, i + 0.5, j + 0.5, col = color_matrix[i, j], border = NA)
    }
  }
}
sorted_clusters <- cluster_assignments[order(cluster_assignments)]
sorted_clusters <- rev(sorted_clusters)  # Flip to match matrix flip
rle_clusters <- rle(sorted_clusters)
cluster_starts <- cumsum(c(1, head(rle_clusters$lengths, -1)))
cluster_ends <- cumsum(rle_clusters$lengths)
cluster_ids <- rle_clusters$values
box_colors <- rev(clust_cols)
for (k in seq_along(cluster_ids)) {
  cluster_id <- cluster_ids[k]
  if (cluster_id == 0) next  # Skip cluster 0 if used for noise
  start_row <- cluster_starts[k]
  end_row <- cluster_ends[k]
  rect(xleft = 0.5, 
    ybottom = start_row - 0.5, 
    xright = nrow(m) + 0.5, 
    ytop = end_row + 0.5, 
    border = box_colors[[k]], 
    lwd = 1.5,
    lty = 2)
}
dev.off()
```

# Dendogram
```{r, dendogram}
pdf("./figures/empirical/empirical_joint_uncertainty_consensus_matrix_hclust_dendogram.pdf", height = 5, width = 5)   
par(mar = c(4.3,4,0.3,0.3))

hclust_obj$height <- log1p(hclust_obj$height)
plot(hclust_obj, labels = FALSE, hang=-1,xlab = "Distance (Ward's D2)",ylab = "ln(Height + 1)",main=NULL,ann = T,sub="",frame.plot = F,axes = T,check = T)
rect.hclust(hclust_obj, k = optimal_k_gap,border = clust_cols)

dev.off()
```


# Log likelihood distribution
```{r loglik distribution} 
pdf("./figures/empirical/empirical_joint_uncertainty_lnlik_dist.pdf", width = 2.5, height = 10)
corHMM:::plot_stacked_densities(joint_ci$lnliks, clusters, cols = clust_cols, main = "", xlab ="", ylab="")
dev.off()
```

# Visualize alternatives clusters results for clade I
```{r alt recon cluster representatives}  
pdf("./figures/empirical/empirical_joint_uncertainty_cluster_representatives.pdf", width = 7.5, height = 15)
to_keep <- corHMM:::get_desc(phy, 417)[corHMM:::get_desc(phy, 417) <= Ntip(phy)]
par(mfrow=c(optimal_k_gap, 1))
for(i in 1:optimal_k_gap){
  clust_id = i 
  phy_tmp <- phy
  index_lowest_dist <- which.min(colMeans(as.matrix(dist_mat)[clusters == clust_id,clusters == clust_id]))
  index_highest_lnlik <- which.max(joint_ci$lnliks[clusters == clust_id])
  max_node_labels <- state_df[clusters == clust_id,][index_lowest_dist,]
  phy_tmp$node.label <- as.numeric(max_node_labels)
  phy_tmp <- keep.tip(phy_tmp, to_keep)
  plot.phylo(phy_tmp, show.tip.label = FALSE, edge.width = 0.5, no.margin = TRUE, direction = "downwards")
  nodelabels(pch = 21, bg = c("white", "black")[as.numeric(phy_tmp$node.label)], cex = 1.5)
  ape::tiplabels(pch = 22,  cex = 1, bg = c("white", "black")[focal$tip.states], col = "black")
}
dev.off()
```

# Important node vizualization
```{r important nodes}
# Calculate importance scores
node_importance <- corHMM:::node_importance_by_cluster(state_df, clusters)

# Look at top nodes for each cluster
important_nodes <- lapply(unique(clusters), function(clust) {
  cluster_nodes <- node_importance[node_importance$cluster == clust,]
  cluster_nodes[(cluster_nodes$importance) > quantile((cluster_nodes$importance), 0.985),]
})

pdf("./figures/empirical/empirical_joint_uncertainty_important_nodes.pdf", width = 13.125, height = 10.5)
par(mfrow=c(1,1))
corHMM:::plot_clustered_phylo(
  phy = phy,
  state_df = state_df,
  cluster_colors = clust_cols,
  cluster_assignments = clusters,
  node_states = joint_ci$best_joint$lik.anc.states,
  important_nodes = important_nodes,
  state_colors = c("grey90", "black"),
  state_labels = c("S", "R"),
  phylogram_params = list(edge.color = "grey50"),
  point_params = list(cex = 1),
  segment_params = list(lty = 3, lwd = 1.5),
  outer_cex = 2, 
  inner_rad = 3, 
  node_offset = 12,
  show_legend=FALSE
)

dev.off()
```