---
title: "Pairwise comparisons as heatmap"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr) 
opts_knit$set(echo = TRUE,warning = FALSE, message = FALSE,error=FALSE,comment=NA) 
opts_chunk$set(echo = TRUE,warning = FALSE, message = FALSE,error=FALSE,comment=NA) 
knitr::opts_knit$set(root.dir = '~/Desktop/gl_mount/Analysis/Phyloaware/joint-uncertainty-ms/') 
```

# Environment
```{r environment, echo=T, message=FALSE, include=T, results=T}
#Packages
packages <- c("tidyverse",'kableExtra','ComplexHeatmap','RColorBrewer','colorRamp2') 

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Source functions
source("./lib/consistent_themes.R")

# Print environment
set.seed(0104) 
Sys.info()
sessionInfo()
```
 
# Load data
```{r}  
phy <- ape::read.tree("./data/empirical/tree/tree.treefile")
dat <- readRDS("./data/empirical/dataset/df.RDS")
dat <- dat[match(phy$tip.label, dat[['isolate_no']]), ]
```

```{r}
genotypes <- readRDS("./data/empirical/resistance_genotypes/resistance_genotypes.RDS") 
genotypes <-  genotypes %>% .[match(phy$tip.label,.[['isolate_no']]),]

df <- left_join(dat,genotypes)
```

# Reconsctructions
```{r}
focals <- readRDS("./data/empirical/joint_reconstruction/phenotype_genotype_focal_asrs.RDS")
joint_uncs <- readRDS("./data/empirical/joint_reconstruction/phenotype_genotype_joint_uncertainty_asrs.RDS")
clustering_str <- readRDS("./data/empirical/joint_reconstruction/hclust_consensus_distance_matrix_seven_clusters_string.RDS")
```

# Pairwise phyloAMR data
```{r}
pairwise_comparisons <- readRDS("./data/empirical/phyloAMR/pairwise_synchronous_transitions_comparisons.RDS")  %>% subset(genotype_reconstruction != 'focal_states') %>% subset(genotype %in% c("AA552","OmpK36_c25t","OmpK36GD","OmpK36TD","OmpK36_promoter_IS","OmpK36_disruptive","PBP_any","RamR","RamA"))
```

## Recode genotypes
```{r}
pairwise_comparisons$genotype <- factor(
pairwise_comparisons$genotype,levels = rev(c("AA552","OmpK36_c25t","OmpK36GD","OmpK36TD","OmpK36_promoter_IS","OmpK36_disruptive","PBP_any","RamR","RamA")))

pairwise_comparisons$genotype <- recode(pairwise_comparisons$genotype , 'OmpK35-25'='ompK35 porin truncation at 25%','OmpK36_c25t'='25 cytosine-to-thymine transition in ompK36','OmpK36_L3_mutations'='Loop 3 insertion in ompK36','OmpK36GD'='GD insertion in loop 3 of ompK36','OmpK36TD'='TD insertion in loop 3 of ompK36','OmpK36_truncation_kleborate'='ompK36 truncation', 'OmpK36_non_syn'='ompK36 non-synonymous mutation','OmpK36_putative_function_altering'='ompK36 PFAV','OmpK36_intergenic'='Mutation in intergenic region of ompK36','OmpK36_promoter_IS'='Insertion seqeunce at ompK36 promoter',"AcrAB_TolC_any" = 'acrAB-tolC efflux pump mutant','RamR'='ramR efflux pump regulator PFAV',"RamA"='ramA efflux pump activator PFAV','PBP_any'='Penicillin-binding-protein mutant','PBP2'='Penicillin-binding protein-2 mutant',"PBP4"='Penicillin-binding protein-4 mutant',"AA018" = "AA018 blaKPC-containing plasmid","AA552" = "AA552 blaKPC-containing plasmid","OmpK36_disruptive" = "Putative disruptive mutation in ompK36") 
```

# Synchronous
```{r,fig.width=12, fig.height=8, results='hide',echo=TRUE}
pairwise_comparisons_ordered <- pairwise_comparisons %>% arrange(genotype,pheno_cluster)
pairwise_comparisons_ordered$genotype_reconstruction_axes <- paste0(pairwise_comparisons_ordered$genotype,"_",pairwise_comparisons_ordered$genotype_reconstruction)

# Pivot wide
cluster_names <- clustering_str %>% `names<-`(seq_len(length(.)))
matrix_of_vals <- pairwise_comparisons_ordered %>%
    group_by(genotype_reconstruction_axes, phenotype_reconstruction) %>%
    summarise(value = synchronous_gains_num) %>%  # or median(), sum(), etc
    pivot_wider(names_from = genotype_reconstruction_axes, values_from = value) 

matrix_of_vals$cluster <- sapply(matrix_of_vals$phenotype_reconstruction,FUN=function(x){
  if(!grepl("focal",x)){
    cluster_names[names(cluster_names) == gsub("alt_recon_","",x)]
  } else {
    x
  }
})

matrix_of_vals$cluster <- recode(matrix_of_vals$cluster,"focal_states" ="Best joint reconstruction",
                                             "1" ="Reconstruction axis 1",
                                             "2" ="Reconstruction axis 2",
                                             "3" ="Reconstruction axis 3",
                                             "4" ="Reconstruction axis 4",
                                             "5" ="Reconstruction axis 5", 
                                             "6" ="Reconstruction axis 6", 
                                             "7" ="Reconstruction axis 7") 

matrix_of_vals <- matrix_of_vals %>% arrange(cluster) 
rowsplit_pheno <- factor(matrix_of_vals$cluster,levels = unique(sort(matrix_of_vals$cluster)))

gene <- factor(colnames(matrix_of_vals %>% select(-cluster, -phenotype_reconstruction)) %>% str_split(.,"_",simplify=T) %>% .[,1:2] %>% apply(.,1,paste0,collapse="_")  %>% gsub("_alt|_focal","",.)) 

phen_colors <- setNames(phylogenetic_reconstruction_scale$palette(length(phylogenetic_reconstruction_scale$breaks)),phylogenetic_reconstruction_scale$breaks)

rowannots <- ComplexHeatmap::rowAnnotation(
  `Phenotype axes` = factor(matrix_of_vals$cluster),
  annotation_name_gp = gpar(fontsize = 0),
  col = list(`Phenotype axes` = phen_colors),
    show_legend = FALSE 
)

genotype_levels <- unique(pairwise_comparisons$genotype  )
genotype_colors <- setNames(hues::iwanthue(length(genotype_levels)), genotype_levels)

colannots <- ComplexHeatmap::columnAnnotation(
  `Genotype` = gene,
  annotation_name_gp = gpar(fontsize = 0),
  col = list(`Genotype` = genotype_colors),
   show_legend = FALSE 
)

max_syn_transitions <- matrix_of_vals %>% select(-cluster, -phenotype_reconstruction) %>% as.matrix() %>% unlist %>% as.vector %>% max

col_fun_syn <- colorRamp2(c(0, max_syn_transitions), c("white", "red"))

A <- Heatmap(
  matrix_of_vals %>% select(-cluster, -phenotype_reconstruction) %>% as.matrix(),
  row_split = rowsplit_pheno,
  column_split = gene,
  cluster_rows = FALSE,
  cluster_row_slices = TRUE,
  cluster_columns = FALSE,
  cluster_column_slices = TRUE,
  col =col_fun_syn,
  show_row_names = FALSE,
  show_column_names = FALSE,
  show_row_dend = FALSE,
  row_title = NULL,
  column_title = NULL,
  right_annotation = rowannots,
  top_annotation = colannots,
  name = "Synchronous gain events",
  heatmap_legend_param =list(at = 0:max_syn_transitions,labels = 0:max_syn_transitions)
) 

A

# Extract legends for each annotation
lgd_row <- color_mapping_legend(rowannots@anno_list[["Phenotype axes"]]@color_mapping)
lgd_col <- color_mapping_legend(colannots@anno_list[["Genotype"]]@color_mapping)

# Pack all legends into one column
merged_legends <- packLegend( 
  lgd_row,
  lgd_col,
  direction = "vertical"
)
```

# Asynchronous
```{r,fig.width=12, fig.height=8, results='hide', echo=TRUE}
# Pivot wide 
matrix_of_vals_asy <- pairwise_comparisons_ordered %>%
    group_by(genotype_reconstruction_axes, phenotype_reconstruction) %>%
    summarise(value = synchronous_losses_num) %>%  # or median(), sum(), etc
    pivot_wider(names_from = genotype_reconstruction_axes, values_from = value) 

matrix_of_vals_asy$cluster <- sapply(matrix_of_vals_asy$phenotype_reconstruction,FUN=function(x){
  if(!grepl("focal",x)){
    cluster_names[names(cluster_names) == gsub("alt_recon_","",x)]
  } else {
    x
  }
})

matrix_of_vals_asy$cluster <- recode(matrix_of_vals_asy$cluster,"focal_states" ="Best joint reconstruction",
                                             "1" ="Reconstruction axis 1",
                                             "2" ="Reconstruction axis 2",
                                             "3" ="Reconstruction axis 3",
                                             "4" ="Reconstruction axis 4",
                                             "5" ="Reconstruction axis 5",
                                             "6" ="Reconstruction axis 6", 
                                             "7" ="Reconstruction axis 7") 

matrix_of_vals_asy <- matrix_of_vals_asy %>% arrange(cluster) 
rowsplit_pheno <- factor(matrix_of_vals_asy$cluster,levels = unique(sort(matrix_of_vals_asy$cluster)))

gene <- factor(colnames(matrix_of_vals_asy %>% select(-cluster, -phenotype_reconstruction)) %>% str_split(.,"_",simplify=T) %>% .[,1:2] %>% apply(.,1,paste0,collapse="_")  %>% gsub("_alt|_focal","",.)) 
 
max_asyn_transitions <- matrix_of_vals_asy %>% select(-cluster, -phenotype_reconstruction) %>% as.matrix() %>% unlist %>% as.vector %>% max

col_fun_asyn <- colorRamp2(c(0, max_asyn_transitions), c("white", "red"))

B <- Heatmap(
  matrix_of_vals_asy %>% select(-cluster, -phenotype_reconstruction) %>% as.matrix(),
  row_split = rowsplit_pheno,
  column_split = gene,
  cluster_rows = FALSE,
  cluster_row_slices = TRUE,
  cluster_columns = FALSE,
  cluster_column_slices = TRUE,
  col = col_fun_asyn,
  show_row_names = FALSE,
  show_column_names = FALSE,
  show_row_dend = FALSE,
  row_title = NULL,
  column_title = NULL,
  right_annotation = rowannots,
  top_annotation = colannots,
  name = "Synchronous loss events",
  heatmap_legend_param =list(at = 0:max_asyn_transitions,labels = 0:max_asyn_transitions)
)

B

# Extract legends for each annotation
lgd_row <- color_mapping_legend(rowannots@anno_list[["Phenotype axes"]]@color_mapping)
lgd_col <- color_mapping_legend(colannots@anno_list[["Genotype"]]@color_mapping)

# Pack all legends into one column
merged_legends_2 <- packLegend( 
  lgd_row,
  lgd_col,
  direction = "vertical"
)
``` 

# Save figures
```{r}
png("./figures/empirical/pairwise_reconstruction_synchronous_transition_comparisons_synchronous_gain_events_heatmap.png", width=12, height=8, units="in", res=900)
draw(
  A,
  heatmap_legend_list = list(merged_legends),
  annotation_legend_list = NULL
)
dev.off()

png("./figures/empirical/pairwise_reconstruction_synchronous_transition_comparisons_synchronous_loss_events_heatmap.png", width=12, height=8, units="in", res=900)
draw(
  B,
  heatmap_legend_list = list(merged_legends),
  annotation_legend_list = NULL
)
dev.off()
```
